-- Insert test gemstones into public.gemstones table
-- These will show up in the app's gemstone list

-- Insert Ruby (if not exists)
INSERT INTO public.gemstones (
  variety,
  chemical_composition,
  crystal_system,
  colors,
  cause_of_color,
  transparency,
  luster,
  hardness,
  sg_min,
  sg_max,
  ri_min,
  ri_max,
  cleavage,
  fracture,
  optic_character,
  pleochroism,
  inclusions,
  uv_response,
  simulants,
  treatments,
  occurrences,
  indian_name,
  category,
  formation,
  testing_guide,
  market_demand,
  price_range_inr_min,
  price_range_inr_max,
  price_range_usd_min,
  price_range_usd_max,
  is_custom
) VALUES (
  'Ruby',
  'Al₂O₃ (Aluminium Oxide)',
  'Trigonal',
  ARRAY['Red', 'Pinkish-red', 'Purple-red', 'Dark red'],
  'Chromium',
  ARRAY['Transparent', 'Translucent', 'Opaque'],
  'Vitreous',
  9,
  3.97,
  4.05,
  1.762,
  1.778,
  'None (lamellar twinning, directional parting)',
  'Conchoidal, uneven',
  'DR (Uniaxial negative)',
  'Strong dichroic (purplish-red to orangish-red)',
  ARRAY['Silk (rutile needles)', 'Crystals', 'Feathers', 'Fingerprints', 'Zoning'],
  'Strong red fluorescence under LW-UV',
  ARRAY['Synthetic ruby', 'Red spinel', 'Garnet', 'Glass', 'Doublets', 'CZ'],
  ARRAY['Heat treatment', 'Lead glass filling', 'Fracture filling', 'Beryllium diffusion'],
  ARRAY['Myanmar (Burma)', 'Sri Lanka', 'Mozambique', 'Thailand', 'Madagascar', 'India'],
  'Manik / Manek',
  'Precious',
  'Forms in metamorphic rocks, particularly marble and gneiss. Requires aluminum-rich, silica-poor environments with trace chromium.',
  ARRAY['Check RI: Should be 1.762-1.778 with birefringence of 0.008', 'Check SG: Should be 3.97-4.05 (heavier than spinel)', 'Look for silk inclusions under magnification', 'Test fluorescence: Strong red under LW-UV (natural) vs weak/no fluorescence (synthetic)', 'Check for curved striae in synthetics vs straight growth lines in natural'],
  'High',
  5000,
  500000,
  60,
  6000,
  false
) ON CONFLICT DO NOTHING;

-- Insert Sapphire (if not exists)
INSERT INTO public.gemstones (
  variety,
  chemical_composition,
  crystal_system,
  colors,
  cause_of_color,
  transparency,
  luster,
  hardness,
  sg_min,
  sg_max,
  ri_min,
  ri_max,
  cleavage,
  fracture,
  optic_character,
  pleochroism,
  inclusions,
  uv_response,
  simulants,
  treatments,
  occurrences,
  indian_name,
  category,
  formation,
  testing_guide,
  market_demand,
  price_range_inr_min,
  price_range_inr_max,
  price_range_usd_min,
  price_range_usd_max,
  is_custom
) VALUES (
  'Sapphire',
  'Al₂O₃ (Aluminium Oxide)',
  'Trigonal',
  ARRAY['Blue', 'Pink', 'Yellow', 'Orange', 'Green', 'Purple', 'Colorless'],
  'Iron and Titanium (blue), Chromium (pink), Iron (yellow/green)',
  ARRAY['Transparent', 'Translucent'],
  'Vitreous',
  9,
  3.98,
  4.06,
  1.762,
  1.778,
  'None (lamellar twinning, directional parting)',
  'Conchoidal, uneven',
  'DR (Uniaxial negative)',
  'Moderate to strong (blue to greenish-blue)',
  ARRAY['Silk (rutile needles)', 'Zoning', 'Crystals', 'Fingerprints', 'Feathers'],
  'Inert to weak fluorescence',
  ARRAY['Synthetic sapphire', 'Blue spinel', 'Tanzanite', 'Iolite', 'Glass', 'CZ'],
  ARRAY['Heat treatment', 'Diffusion treatment', 'Beryllium diffusion', 'Lattice diffusion'],
  ARRAY['Sri Lanka', 'Myanmar (Burma)', 'Kashmir (India)', 'Thailand', 'Madagascar', 'Australia', 'Montana (USA)'],
  'Neelam (Blue) / Pukhraj (Yellow)',
  'Precious',
  'Forms in metamorphic and igneous rocks. Blue sapphires typically form in aluminum-rich, silica-poor environments with iron and titanium.',
  ARRAY['Check RI: Should be 1.762-1.778', 'Check SG: Should be 3.98-4.06', 'Look for silk inclusions and zoning', 'Test for asterism (star sapphires)', 'Check for color zoning and growth patterns'],
  'High',
  3000,
  300000,
  36,
  3600,
  false
) ON CONFLICT DO NOTHING;

-- Insert Emerald (if not exists)
INSERT INTO public.gemstones (
  variety,
  chemical_composition,
  crystal_system,
  colors,
  cause_of_color,
  transparency,
  luster,
  hardness,
  sg_min,
  sg_max,
  ri_min,
  ri_max,
  cleavage,
  fracture,
  optic_character,
  pleochroism,
  inclusions,
  uv_response,
  simulants,
  treatments,
  occurrences,
  indian_name,
  category,
  formation,
  testing_guide,
  market_demand,
  price_range_inr_min,
  price_range_inr_max,
  price_range_usd_min,
  price_range_usd_max,
  is_custom
) VALUES (
  'Emerald',
  'Be₃Al₂(SiO₃)₆ (Beryllium Aluminium Silicate)',
  'Hexagonal',
  ARRAY['Green', 'Bluish-green', 'Yellowish-green'],
  'Chromium and Vanadium',
  ARRAY['Transparent', 'Translucent'],
  'Vitreous',
  7.5,
  2.67,
  2.78,
  1.565,
  1.602,
  'Indistinct (one direction)',
  'Conchoidal, uneven',
  'DR (Uniaxial negative)',
  'Moderate green to bluish-green',
  ARRAY['Three-phase inclusions', 'Jardin (garden)', 'Fingerprints', 'Crystals', 'Feathers', 'Actinolite needles'],
  'Inert to weak red fluorescence',
  ARRAY['Synthetic emerald', 'Green tourmaline', 'Green glass', 'Peridot', 'Green sapphire', 'CZ'],
  ARRAY['Oiling (cedar oil)', 'Resin filling', 'Fracture filling', 'Dyeing'],
  ARRAY['Colombia', 'Zambia', 'Brazil', 'Afghanistan', 'India', 'Zimbabwe', 'Russia'],
  'Panna',
  'Precious',
  'Forms in pegmatites and hydrothermal veins. Requires beryllium, aluminum, silicon, and trace chromium or vanadium in low-temperature, high-pressure conditions.',
  ARRAY['Check RI: Should be 1.565-1.602', 'Check SG: Should be 2.67-2.78', 'Look for characteristic three-phase inclusions', 'Check for jardin (garden) - internal fractures', 'Test for oil/resin filling with UV light'],
  'High',
  8000,
  800000,
  96,
  9600,
  false
) ON CONFLICT DO NOTHING;


