import React, { useState } from "react";
import { 
  StyleSheet, 
  View, 
  Pressable, 
  Modal,
  ScrollView,
  Share,
  Platform,
} from "react-native";
import { Feather } from "@expo/vector-icons";

import { ScreenKeyboardAwareScrollView } from "@/components/ScreenKeyboardAwareScrollView";
import { ThemedText } from "@/components/ThemedText";
import { ThemedView } from "@/components/ThemedView";
import { Card } from "@/components/Card";
import { Input } from "@/components/Input";
import { Dropdown } from "@/components/Dropdown";
import { ChipSelect } from "@/components/ChipSelect";
import { Button } from "@/components/Button";
import { useTheme } from "@/hooks/useTheme";
import { Spacing, BorderRadius, Shadows } from "@/constants/theme";
import { 
  GEMSTONE_DATABASE, 
  TREATMENT_OPTIONS,
  COMMON_INCLUSIONS,
} from "@/constants/gemstoneData";

export default function CertificateScreen() {
  const { theme } = useTheme();
  
  const [showPreview, setShowPreview] = useState(false);
  const [formData, setFormData] = useState({
    stoneName: "",
    weight: "",
    dimensions: { length: "", width: "", depth: "" },
    color: "",
    riMin: "",
    riMax: "",
    sg: "",
    inclusions: [] as string[],
    treatment: "",
    origin: "",
    comments: "",
    certNumber: `GEM-${Date.now().toString(36).toUpperCase()}`,
  });

  const updateForm = (key: string, value: any) => {
    setFormData(prev => ({ ...prev, [key]: value }));
  };

  const updateDimension = (key: string, value: string) => {
    setFormData(prev => ({
      ...prev,
      dimensions: { ...prev.dimensions, [key]: value },
    }));
  };

  const handleShare = async () => {
    try {
      await Share.share({
        message: `Gemstone Certificate\n\nCertificate No: ${formData.certNumber}\nStone: ${formData.stoneName}\nWeight: ${formData.weight} ct\nColor: ${formData.color}\nRI: ${formData.riMin} - ${formData.riMax}\nSG: ${formData.sg}\nTreatment: ${formData.treatment || "None"}\nOrigin: ${formData.origin || "Not specified"}\n\nGenerated by GemAI Pro`,
        title: "Gemstone Certificate",
      });
    } catch (error) {
      console.error("Share failed:", error);
    }
  };

  const resetForm = () => {
    setFormData({
      stoneName: "",
      weight: "",
      dimensions: { length: "", width: "", depth: "" },
      color: "",
      riMin: "",
      riMax: "",
      sg: "",
      inclusions: [],
      treatment: "",
      origin: "",
      comments: "",
      certNumber: `GEM-${Date.now().toString(36).toUpperCase()}`,
    });
  };

  const isFormValid = formData.stoneName && formData.weight && formData.color;

  return (
    <>
      <ScreenKeyboardAwareScrollView>
        <Card style={styles.certNumberCard}>
          <View style={styles.certNumberRow}>
            <View>
              <ThemedText type="caption" style={{ color: theme.textSecondary }}>
                CERTIFICATE NUMBER
              </ThemedText>
              <ThemedText type="mono" style={styles.certNumber}>
                {formData.certNumber}
              </ThemedText>
            </View>
            <Pressable
              onPress={() => updateForm("certNumber", `GEM-${Date.now().toString(36).toUpperCase()}`)}
              style={({ pressed }) => [
                styles.refreshButton,
                { backgroundColor: theme.primary + "20", opacity: pressed ? 0.7 : 1 }
              ]}
            >
              <Feather name="refresh-cw" size={16} color={theme.primary} />
            </Pressable>
          </View>
        </Card>

        <ThemedText type="small" style={[styles.sectionLabel, { color: theme.textSecondary }]}>
          STONE INFORMATION
        </ThemedText>
        
        <Card style={styles.formCard}>
          <Dropdown
            label="Stone Name"
            placeholder="Select gemstone"
            value={formData.stoneName}
            options={GEMSTONE_DATABASE.map(g => g.variety)}
            onSelect={(val) => updateForm("stoneName", val)}
          />
          <View style={styles.formSpacer} />
          
          <View style={styles.formRow}>
            <View style={{ flex: 1 }}>
              <Input
                label="Weight (ct)"
                placeholder="2.50"
                value={formData.weight}
                onChangeText={(val) => updateForm("weight", val)}
                keyboardType="decimal-pad"
                mono
              />
            </View>
            <View style={{ flex: 1 }}>
              <Input
                label="Color"
                placeholder="Vivid Red"
                value={formData.color}
                onChangeText={(val) => updateForm("color", val)}
              />
            </View>
          </View>
        </Card>

        <ThemedText type="small" style={[styles.sectionLabel, { color: theme.textSecondary }]}>
          DIMENSIONS (MM)
        </ThemedText>
        
        <Card style={styles.formCard}>
          <View style={styles.formRow}>
            <View style={{ flex: 1 }}>
              <Input
                label="Length"
                placeholder="8.5"
                value={formData.dimensions.length}
                onChangeText={(val) => updateDimension("length", val)}
                keyboardType="decimal-pad"
                mono
              />
            </View>
            <View style={{ flex: 1 }}>
              <Input
                label="Width"
                placeholder="6.5"
                value={formData.dimensions.width}
                onChangeText={(val) => updateDimension("width", val)}
                keyboardType="decimal-pad"
                mono
              />
            </View>
            <View style={{ flex: 1 }}>
              <Input
                label="Depth"
                placeholder="4.2"
                value={formData.dimensions.depth}
                onChangeText={(val) => updateDimension("depth", val)}
                keyboardType="decimal-pad"
                mono
              />
            </View>
          </View>
        </Card>

        <ThemedText type="small" style={[styles.sectionLabel, { color: theme.textSecondary }]}>
          GEMOLOGICAL DATA
        </ThemedText>
        
        <Card style={styles.formCard}>
          <View style={styles.formRow}>
            <View style={{ flex: 1 }}>
              <Input
                label="RI Min"
                placeholder="1.762"
                value={formData.riMin}
                onChangeText={(val) => updateForm("riMin", val)}
                keyboardType="decimal-pad"
                mono
              />
            </View>
            <View style={{ flex: 1 }}>
              <Input
                label="RI Max"
                placeholder="1.778"
                value={formData.riMax}
                onChangeText={(val) => updateForm("riMax", val)}
                keyboardType="decimal-pad"
                mono
              />
            </View>
            <View style={{ flex: 1 }}>
              <Input
                label="SG"
                placeholder="3.99"
                value={formData.sg}
                onChangeText={(val) => updateForm("sg", val)}
                keyboardType="decimal-pad"
                mono
              />
            </View>
          </View>
        </Card>

        <ThemedText type="small" style={[styles.sectionLabel, { color: theme.textSecondary }]}>
          CHARACTERISTICS
        </ThemedText>
        
        <Card style={styles.formCard}>
          <ChipSelect
            label="Inclusions Observed"
            options={COMMON_INCLUSIONS}
            selected={formData.inclusions}
            onSelect={(val) => updateForm("inclusions", val)}
          />
          <View style={styles.formSpacer} />
          
          <Dropdown
            label="Treatment"
            placeholder="Select treatment"
            value={formData.treatment}
            options={[...TREATMENT_OPTIONS]}
            onSelect={(val) => updateForm("treatment", val)}
          />
          <View style={styles.formSpacer} />
          
          <Input
            label="Origin"
            placeholder="Myanmar, Sri Lanka, etc."
            value={formData.origin}
            onChangeText={(val) => updateForm("origin", val)}
          />
        </Card>

        <ThemedText type="small" style={[styles.sectionLabel, { color: theme.textSecondary }]}>
          ADDITIONAL COMMENTS
        </ThemedText>
        
        <Card style={styles.formCard}>
          <Input
            placeholder="Any additional notes or observations..."
            value={formData.comments}
            onChangeText={(val) => updateForm("comments", val)}
            multiline
            style={styles.commentsInput}
          />
        </Card>

        <View style={styles.buttonRow}>
          <Pressable
            onPress={resetForm}
            style={({ pressed }) => [
              styles.secondaryButton,
              { 
                backgroundColor: theme.backgroundSecondary,
                opacity: pressed ? 0.7 : 1,
              }
            ]}
          >
            <Feather name="refresh-cw" size={18} color={theme.text} />
            <ThemedText type="body">Reset</ThemedText>
          </Pressable>
          
          <Pressable
            onPress={() => setShowPreview(true)}
            disabled={!isFormValid}
            style={({ pressed }) => [
              styles.primaryButton,
              { 
                backgroundColor: theme.primary,
                opacity: !isFormValid ? 0.5 : pressed ? 0.8 : 1,
              }
            ]}
          >
            <Feather name="eye" size={18} color="#FFFFFF" />
            <ThemedText type="body" style={{ color: "#FFFFFF" }}>Preview</ThemedText>
          </Pressable>
        </View>

        <View style={styles.bottomSpacer} />
      </ScreenKeyboardAwareScrollView>

      <Modal
        visible={showPreview}
        animationType="slide"
        presentationStyle="pageSheet"
        onRequestClose={() => setShowPreview(false)}
      >
        <ThemedView style={styles.modalContainer}>
          <View style={styles.modalHeader}>
            <ThemedText type="h4">Certificate Preview</ThemedText>
            <Pressable
              onPress={() => setShowPreview(false)}
              style={({ pressed }) => [{ opacity: pressed ? 0.6 : 1 }]}
            >
              <Feather name="x" size={24} color={theme.text} />
            </Pressable>
          </View>

          <ScrollView style={styles.previewScroll}>
            <View style={[styles.certificate, { backgroundColor: "#FFFFFF" }]}>
              <View style={styles.certHeader}>
                <View style={[styles.logoPlaceholder, { backgroundColor: theme.primary }]}>
                  <Feather name="hexagon" size={32} color="#FFFFFF" />
                </View>
                <ThemedText type="h3" lightColor="#1F2937" darkColor="#1F2937">
                  GemAI Pro
                </ThemedText>
                <ThemedText type="caption" lightColor="#6B7280" darkColor="#6B7280">
                  GEMOLOGICAL ANALYSIS CERTIFICATE
                </ThemedText>
              </View>

              <View style={[styles.certDivider, { backgroundColor: theme.primary }]} />

              <View style={styles.certBody}>
                <View style={styles.certRow}>
                  <ThemedText type="caption" lightColor="#6B7280" darkColor="#6B7280">
                    CERTIFICATE NO.
                  </ThemedText>
                  <ThemedText type="mono" lightColor="#1F2937" darkColor="#1F2937">
                    {formData.certNumber}
                  </ThemedText>
                </View>

                <View style={styles.certRow}>
                  <ThemedText type="caption" lightColor="#6B7280" darkColor="#6B7280">
                    STONE IDENTIFICATION
                  </ThemedText>
                  <ThemedText type="body" lightColor="#1F2937" darkColor="#1F2937" style={{ fontWeight: "600" }}>
                    {formData.stoneName || "—"}
                  </ThemedText>
                </View>

                <View style={styles.certRow}>
                  <ThemedText type="caption" lightColor="#6B7280" darkColor="#6B7280">
                    WEIGHT
                  </ThemedText>
                  <ThemedText type="mono" lightColor="#1F2937" darkColor="#1F2937">
                    {formData.weight ? `${formData.weight} ct` : "—"}
                  </ThemedText>
                </View>

                <View style={styles.certRow}>
                  <ThemedText type="caption" lightColor="#6B7280" darkColor="#6B7280">
                    DIMENSIONS
                  </ThemedText>
                  <ThemedText type="mono" lightColor="#1F2937" darkColor="#1F2937">
                    {formData.dimensions.length && formData.dimensions.width && formData.dimensions.depth
                      ? `${formData.dimensions.length} x ${formData.dimensions.width} x ${formData.dimensions.depth} mm`
                      : "—"}
                  </ThemedText>
                </View>

                <View style={styles.certRow}>
                  <ThemedText type="caption" lightColor="#6B7280" darkColor="#6B7280">
                    COLOR
                  </ThemedText>
                  <ThemedText type="body" lightColor="#1F2937" darkColor="#1F2937">
                    {formData.color || "—"}
                  </ThemedText>
                </View>

                <View style={styles.certRow}>
                  <ThemedText type="caption" lightColor="#6B7280" darkColor="#6B7280">
                    REFRACTIVE INDEX
                  </ThemedText>
                  <ThemedText type="mono" lightColor="#1F2937" darkColor="#1F2937">
                    {formData.riMin && formData.riMax 
                      ? `${formData.riMin} - ${formData.riMax}` 
                      : "—"}
                  </ThemedText>
                </View>

                <View style={styles.certRow}>
                  <ThemedText type="caption" lightColor="#6B7280" darkColor="#6B7280">
                    SPECIFIC GRAVITY
                  </ThemedText>
                  <ThemedText type="mono" lightColor="#1F2937" darkColor="#1F2937">
                    {formData.sg || "—"}
                  </ThemedText>
                </View>

                <View style={styles.certRow}>
                  <ThemedText type="caption" lightColor="#6B7280" darkColor="#6B7280">
                    INCLUSIONS
                  </ThemedText>
                  <ThemedText type="body" lightColor="#1F2937" darkColor="#1F2937">
                    {formData.inclusions.length > 0 
                      ? formData.inclusions.join(", ") 
                      : "None observed"}
                  </ThemedText>
                </View>

                <View style={styles.certRow}>
                  <ThemedText type="caption" lightColor="#6B7280" darkColor="#6B7280">
                    TREATMENT
                  </ThemedText>
                  <ThemedText type="body" lightColor="#1F2937" darkColor="#1F2937">
                    {formData.treatment || "None"}
                  </ThemedText>
                </View>

                <View style={styles.certRow}>
                  <ThemedText type="caption" lightColor="#6B7280" darkColor="#6B7280">
                    ORIGIN
                  </ThemedText>
                  <ThemedText type="body" lightColor="#1F2937" darkColor="#1F2937">
                    {formData.origin || "Not specified"}
                  </ThemedText>
                </View>

                {formData.comments ? (
                  <View style={styles.commentsSection}>
                    <ThemedText type="caption" lightColor="#6B7280" darkColor="#6B7280">
                      COMMENTS
                    </ThemedText>
                    <ThemedText type="small" lightColor="#1F2937" darkColor="#1F2937">
                      {formData.comments}
                    </ThemedText>
                  </View>
                ) : null}
              </View>

              <View style={styles.certFooter}>
                <View style={styles.qrPlaceholder}>
                  <Feather name="grid" size={40} color="#9CA3AF" />
                  <ThemedText type="caption" lightColor="#9CA3AF" darkColor="#9CA3AF">
                    QR Code
                  </ThemedText>
                </View>
                <View style={styles.signaturePlaceholder}>
                  <View style={[styles.signatureLine, { borderBottomColor: "#9CA3AF" }]} />
                  <ThemedText type="caption" lightColor="#6B7280" darkColor="#6B7280">
                    Authorized Signature
                  </ThemedText>
                </View>
              </View>
            </View>
          </ScrollView>

          <View style={[styles.modalFooter, { borderTopColor: theme.border }]}>
            <Pressable
              onPress={handleShare}
              style={({ pressed }) => [
                styles.footerButton,
                { 
                  backgroundColor: theme.backgroundSecondary,
                  opacity: pressed ? 0.8 : 1,
                },
              ]}
            >
              <Feather name="share-2" size={18} color={theme.text} />
              <ThemedText type="body">Share</ThemedText>
            </Pressable>
            <Pressable
              onPress={() => setShowPreview(false)}
              style={({ pressed }) => [
                styles.footerButton,
                { 
                  backgroundColor: theme.primary,
                  opacity: pressed ? 0.8 : 1,
                },
              ]}
            >
              <Feather name="check" size={18} color="#FFFFFF" />
              <ThemedText type="body" style={{ color: "#FFFFFF" }}>Done</ThemedText>
            </Pressable>
          </View>
        </ThemedView>
      </Modal>
    </>
  );
}

const styles = StyleSheet.create({
  certNumberCard: {
    marginBottom: Spacing.lg,
  },
  certNumberRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  certNumber: {
    fontSize: 18,
    marginTop: Spacing.xs,
  },
  refreshButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  sectionLabel: {
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: Spacing.sm,
    marginTop: Spacing.md,
  },
  formCard: {
    marginBottom: Spacing.sm,
  },
  formSpacer: {
    height: Spacing.md,
  },
  formRow: {
    flexDirection: "row",
    gap: Spacing.md,
  },
  commentsInput: {
    height: 80,
    textAlignVertical: "top",
    paddingTop: Spacing.md,
  },
  buttonRow: {
    flexDirection: "row",
    gap: Spacing.md,
    marginTop: Spacing.xl,
  },
  secondaryButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.sm,
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.xs,
  },
  primaryButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.sm,
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.xs,
  },
  bottomSpacer: {
    height: Spacing["4xl"],
  },
  modalContainer: {
    flex: 1,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: Spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(128,128,128,0.2)",
  },
  previewScroll: {
    flex: 1,
    padding: Spacing.lg,
  },
  certificate: {
    borderRadius: BorderRadius.sm,
    overflow: "hidden",
    ...Shadows.lg,
  },
  certHeader: {
    alignItems: "center",
    paddingVertical: Spacing.xl,
    paddingHorizontal: Spacing.lg,
  },
  logoPlaceholder: {
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: Spacing.md,
  },
  certDivider: {
    height: 3,
  },
  certBody: {
    padding: Spacing.lg,
  },
  certRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: Spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  commentsSection: {
    marginTop: Spacing.md,
    paddingTop: Spacing.md,
    borderTopWidth: 1,
    borderTopColor: "#E5E7EB",
  },
  certFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    padding: Spacing.lg,
    paddingTop: Spacing.xl,
    borderTopWidth: 1,
    borderTopColor: "#E5E7EB",
  },
  qrPlaceholder: {
    width: 80,
    height: 80,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: BorderRadius.xs,
    alignItems: "center",
    justifyContent: "center",
  },
  signaturePlaceholder: {
    alignItems: "center",
  },
  signatureLine: {
    width: 120,
    borderBottomWidth: 1,
    marginBottom: Spacing.xs,
  },
  modalFooter: {
    flexDirection: "row",
    gap: Spacing.md,
    padding: Spacing.lg,
    borderTopWidth: 1,
  },
  footerButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.sm,
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.xs,
  },
});
